config/routes.rb
Track::Application.routes.draw do

  get "maildev" => 'emaildev#index'

  get "welcome" => "application#welcome", path: "/shop/welcome/"
  get "return_order_test" => "application#return_order_test", path: 'shop/return_order_test'
  post "return_order" => "application#return_order", path: 'shop/return_order'
  post "mailchimp/subscribe" => "mailchimp#subscribe"
  post "mailchimp/subscribe_footer" => "mailchimp#subscribe_footer"
  post "mailchimp/notify_me" => "mailchimp#notify_me"

  resources 'referrals', except: [:delete, :update, :edit]
  post 'referrals/subscribe' => 'referrals#subscribe', as: :subscribe_referral
  get 'spreadtheword' => 'referrals#new', as: :create_referral

  match "/products", :to => redirect("/men"), via: :get
  match "/womens", :to => redirect("/women"), via: :get

  get "men" => "application#men", path: "/men"
  get "women" => "application#women", path: "/women"

  mount Spree::Core::Engine, :at => '/shop'

  mount Alchemy::Engine => '/', :as => 'alchemy'

  Spree::Core::Engine.draw_routes

end

app/models/alchemy/element_decorator.rb
# == Schema Information
#
# Table name: alchemy_elements
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  position        :integer
#  page_id         :integer
#  public          :boolean          default(TRUE)
#  folded          :boolean          default(FALSE)
#  unique          :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  creator_id      :integer
#  updater_id      :integer
#  cell_id         :integer
#  cached_tag_list :text
#

Alchemy::Element.class_eval do
  has_many :contents, -> { order(:created_at) }, dependent: :destroy
end


    
   

app/models/alchemy/essence_picture_decorator.rb
Alchemy::EssencePicture.class_eval do

  #if Rails.env.production? || Rails.env.staging? || Rails.env.prod_mockup?
    def picture_url(options = {})
      return if picture.nil?
       params = picture_params(options)
       return picture.image_file.remote_url(host: "#{CLOUDFRONT_CONFIG['image_domain']}.#{CLOUDFRONT_CONFIG['host']}") if params[:crop].nil?
       routes.show_picture_path(params)
    end
end

app/models/alchemy/essence_spree_product.rb
module Alchemy
  class EssenceSpreeProduct < ActiveRecord::Base
    belongs_to :product, class_name: "Spree::Product", foreign_key: 'spree_product_id', readonly: true

    acts_as_essence(
      ingredient_column: 'spree_product_id',
      preview_text_method: 'name'
    )

    def ingredient
      product
    end
  end
end

app/models/alchemy/essence_spree_taxon.rb
module Alchemy
  class EssenceSpreeTaxon < ActiveRecord::Base
    belongs_to :taxon, class_name: "Spree::Taxon", foreign_key: 'taxon_id', readonly: true

    acts_as_essence(
      ingredient_column: 'taxon_id',
      preview_text_method: 'name'
    )

    def ingredient
      taxon
    end
  end
end

app/controllers/alchemy/pages_controller.rb
module Alchemy
  class PagesController < Alchemy::BaseController
    # We need to include this helper because we need the breadcrumb method.
    # And we cannot define the breadcrump method as helper_method, because rspec does not see helper_methods.
    # Not the best solution, but's working.
    # Anyone with a better idea please provide a patch.
    include Alchemy::BaseHelper

    rescue_from ActionController::RoutingError, :with => :render_404

    before_filter :enforce_primary_host_for_site
    before_filter :render_page_or_redirect, :only => [:show]
    before_filter :load_page
    # authorize_resource only: 'show'

    # Showing page from params[:urlname]
    #
    def show
      if render_fresh_page?
        respond_to do |format|
          format.html { render layout: !request.xhr? }
          format.rss do
            if @page.contains_feed?
              render action: 'show', layout: false, handlers: [:builder]
            else
              render xml: {error: 'Not found'}, status: 404
            end
          end
          format.json { render json: @page }
        end
      end
    end

    # Renders a search engine compatible xml sitemap.
    def sitemap
      @pages = Page.sitemap
      respond_to do |format|
        format.xml { render layout: 'alchemy/sitemap' }
      end
    end

    private

    # Load the current page and store it in @page.
    #
    def load_page
      @page ||= if params[:urlname].present?
        # Load by urlname. If a language is specified in the request parameters,
        # scope pages to it to make sure we can raise a 404 if the urlname
        # is not available in that language.
        Page.contentpages.where(
          urlname:       params[:urlname],
          language_id:   Language.current.id,
          language_code: params[:lang] || Language.current.code
        ).first
      else
        # No urlname was given, so just load the language root for the
        # currently active language.
        Language.current_root_page
      end
    end

    def enforce_primary_host_for_site
      if needs_redirect_to_primary_host?
        redirect_to url_for(host: current_alchemy_site.host), :status => 301
      end
    end

    def needs_redirect_to_primary_host?
      current_alchemy_site.redirect_to_primary_host? &&
        current_alchemy_site.host != '*' &&
        current_alchemy_site.host != request.host
    end

    def render_page_or_redirect
      @page ||= load_page
      if admin_sign_in_required?
        redirect_to spree_login_path
      elsif @page.nil? && last_legacy_url
        @page = last_legacy_url.page
        redirect_page
      elsif @page.blank?
        raise_not_found_error
      elsif user_sign_in_required?
        session['spree_user_return_to'] = request.path
        redirect_to spree.login_path, flash: {notice: t('flash_notice.sign_in_content')}
      elsif multi_language? && params[:lang].blank?
        redirect_page(lang: Language.current.code)
      elsif multi_language? && params[:urlname].blank? && !params[:lang].blank? && configuration(:redirect_index)
        redirect_page(lang: params[:lang])
      elsif configuration(:redirect_to_public_child) && !@page.public?
        redirect_to_public_child
      elsif params[:urlname].blank? && configuration(:redirect_index)
        redirect_page
      elsif !multi_language? && !params[:lang].blank?
        redirect_page
      elsif @page.has_controller?
        redirect_to main_app.url_for(@page.controller_and_action)
      else
        # setting the language to page.language to be sure it's correct
        set_alchemy_language(@page.language)
        if params[:urlname].blank?
          @root_page = @page
        else
          @root_page = Language.current_root_page
        end
      end
    end

    def admin_sign_in_required?
      if Alchemy.user_class.respond_to?(:admins)
        Alchemy.user_class.admins.size == 0 && @page.nil?
      end
    end

    def user_sign_in_required?
      @page.restricted && !spree_user_signed_in?
    end

    def redirect_to_public_child
      @page = @page.self_and_descendants.published.not_restricted.first
      if @page
        redirect_page
      else
        raise_not_found_error
      end
    end

    def redirect_page(options={})
      defaults = {
        :lang => (multi_language? ? @page.language_code : nil),
        :urlname => @page.urlname
      }
      options = defaults.merge(options)
      redirect_to show_page_path(additional_params.merge(options)), :status => 301
    end

    def additional_params
      params.each do |key, value|
        params[key] = nil if ["action", "controller", "urlname", "lang"].include?(key)
      end
    end

    def legacy_urls
      LegacyPageUrl.joins(:page).where(urlname: params[:urlname], alchemy_pages: {language_id: Language.current.id})
    end

    def last_legacy_url
      legacy_urls.last
    end

    # Returns true if the page cache control headers should be set.
    #
    # == Disable Alchemy's page caching globally
    #
    #     # config/alchemy/config.yml
    #     ...
    #     cache_pages: false
    #
    # == Disable caching on page layout level
    #
    #     # config/alchemy/page_layouts.yml
    #     - name: contact
    #       cache: false
    #
    # Note: This only sets the cache control headers and skips rendering of the page body, if the cache is fresh.
    # This does not disable the fragment caching in the views. So if you don't want a page and it's elements to be cached,
    # then be sure to not use <% cache element %> in the views.
    #
    # @returns Boolean
    #
    def cache_page?
      return false unless @page && Alchemy::Config.get(:cache_pages)
      page_layout = PageLayout.get(@page.page_layout)
      page_layout['cache'] != false && page_layout['searchresults'] != true
    end

    # Returns the etag used for response headers.
    #
    # If a user is logged in, we append theirs etag to prevent caching of user related content.
    #
    # IMPORTANT: If your user does not have a +cache_key+ method (i.e. it's not an ActiveRecord model),
    # you have to ensure to implement it and return a unique identifier for that particular user.
    # Otherwise all users will see the same cached page, regardless of user's state.
    #
    def page_etag
      @page.cache_key + current_alchemy_user.try(:cache_key).to_s
    end

    # We only render the page if either the cache is disabled for this page
    # or the cache is stale, because it's been republished by the user.
    #
    def render_fresh_page?
      !cache_page? || stale?(etag: page_etag,
        last_modified: @page.published_at,
        public: !@page.restricted)
    end

  end
end

app/helpers/alchemy/page_helper.rb
module Alchemy
  module PageHelper
    def image_for_platform(element)
      background_image = element.essence(:background_image)
      mobile_image = element.essence(:mobile_image)
      
      if (is_mobile_device? || is_tablet_device?) && mobile_image.picture_url.present?
        mobile_image
      else
        background_image
      end
    end
  end
end

app/views/alchemy/shared/_footer.html.erb
<div class="top-bar bg-color <%= topbg %>">
  <a href="#top" class="back-to-top">
    <div class="top-arrow-img">
      <%= image_tag 'icons/arrow-up.png' %>
    </div>
    <div>Back To Top</div>
  </a>
</div>
<div class="footer-bg bg-color
  <% if bgcolor %><%= bgcolor %>
  <% end %>"
     <% if bgimageurl %>style="background: url('<%= bgimageurl %>') no-repeat center center; background-size: cover"
     <% end %>>

  <div class="footer-email">
    <%= form_tag('/mailchimp/subscribe_footer', method: "post", id: "footer-form", remote: true, class: "email-form") do %>
        <%= email_field(:email, :address, {id: "email", placeholder: "Enter Your Email", class: "email-input"}) %>
        <%= submit_tag("Join", class: "btn-primary", :onClick => "ga('send', 'event', { eventCategory: 'email', eventAction: 'capture', eventLabel: '" + galabel + "', eventValue: 1});") %>
    <% end %>

    <div id="footer-response"></div>
    <p>Sign up to be the first to learn about new product introductions, restocks and events.</p>

  </div>

  <div class="social">
    <h4>Follow Us</h4>

    <div class="social-row">
      <a class="share-icon footer-twitter" href="http://twitter.com/tracksmith" target="_blank"></a>
      <a class="share-icon footer-fb" href="http://www.facebook.com/tracksmithrunning" target="_blank"></a>
      <a class="share-icon footer-instagram" href="http://www.instagram.com/tracksmithrunning" target="_blank"></a>
      <a class="share-icon footer-tumblr" href="http://tracksmithrunning.tumblr.com" target="_blank"></a>
    </div>
  </div>
  <div class="footer-pages">
    <ul class="link-group link-group-mobile">
      <li><a href="mailto:support@tracksmith.com">support@tracksmith.com</a></li>
    </ul>
    <ul class="pages-left link-group">
      <li><span>&copy;</span> 2014 Tracksmith</li>
    </ul>
    <ul class="pages-mid link-group">
      <li><a href="http://www.tracksmith.com/terms">Terms & Conditions</a></li>
      <li><a href="http://www.tracksmith.com/privacy-policy">Privacy Policy</a></li>
      <li><a href="http://www.tracksmith.com/about">About Us</a></li>
      <li><a href="http://www.tracksmith.com/faqs">FAQs</a></li>
    </ul>

    <ul class="pages-right link-group">
      <li>781.235.0027</li>
      <li><a href="mailto:support@tracksmith.com">support@tracksmith.com</a></li>
    </ul>
    <ul class="link-group link-group-mobile link-group-credits">
      <li class="copyright"><span>&copy;</span> 2014 Tracksmith</li>
    </ul>
  </div>
</div>

app/views/alchemy/shared/_header.html.erb
<header id="header" class="row" data-hook>
  <%=render :partial => 'alchemy/shared/minicart' %>
  <div class="nav standard-nav">
    <ul class="nav-links">
       <li><a href="/men">Men</a></li>
       <li><a href="/women">Women</a></li>
       <li>
        <a href="/">
          <figure id="logo" class="columns six" data-hook><%= image_tag 'logo/logo.png'%></figure>
        </a>
      </li>


      <li id="cart-wrapper">
      <span id="link-to-cart" data-hook>

          <%= link_to Spree.t(:cart), '/cart' %>

      </span>


    </li>

    <!-- from spree_auth_devise -->
    <% if spree_current_user %>
      <li class="account"><a href="/shop/account">Account</a>
        <div class="arrow-up"></div>
        <ul class="account-dropdown">
          <li class="account-link"><a href="/shop/account#dashboard">Account Information</a></li>
          <li class="account-link"><a href="/shop/account#addresses">Address Book</a></li>
          <li class="account-link"><a href="/shop/account#orders">Order History</a></li>
          <li class="account-link"><a href="/shop/account#credits">Credits</a></li>
          <li class="account-link"><a href="/shop/account#returns">Returns &amp; Exchanges</a></li>
          <li class=""><%= link_to Spree.t(:logout), spree.logout_path %></li>
        </ul>
      </li>


    <% else %>
      <li id="link-to-login"><%= link_to Spree.t(:login), spree.login_path %></li>
    <% end %>

    </ul>
  </div>
  <div class="nav mobile-nav">
    <div class="mobile-links">
    <ul class="">
      <div class="close-nav"></div>
      <li><a href="/men">Men</a></li>
      <li><a href="/women">Women</a></li>

      <% if spree_current_user %>

      <li class="account-link"><a href="/shop/account#dashboard">Account Information</a></li>
      <li class="account-link"><a href="/shop/account#addresses">Address Book</a></li>
      <li class="account-link"><a href="/shop/account#orders">Order History</a></li>
      <li class="account-link"><a href="/shop/account#credits">Credits</a></li>
      <li class="account-link"><a href="/shop/account#returns">Returns &amp; Exchanges</a></li>
      <li><%= link_to Spree.t(:logout), spree.logout_path %></li>

      <% else %>
        <li id="link-to-login"><%= link_to Spree.t(:login), spree.login_path %></li>
      <% end %>

    </ul>
  </div>
    <ul class="nav-links">
      <li class="hamburger-nav">
        <div class="icon-burger"></div>
      </li>
      <li class="logo">
       <a href="/">
          <figure id="logo" class="columns six" data-hook><%= image_tag "logo/logo.png"%></figure>
        </a>
      </li>
          <li id="cart-wrapper">
      <span id="mobile-link-to-cart" data-hook>
          <%= link_to 'Cart', '/cart' %>
      </span>


    </li>

    </ul>
  </div>

</header>

app/views/alchemy/shared/_intro.html.erb
<section id="homepage-intro">
  <div class="background_image_module" style="background: url('<%= asset_path('homepage/intro/bg.jpg') %>') no-repeat center center; background-size: cover; height: 100% ">
    <div class="module-content center-center white">
      <div class="module-text">
        <%= image_tag "homepage/intro/logo.png", style: "display: inline-block;" %>
      </div>
    </div>
  </div>
</section>

app/views/alchemy/shared/_minicart.html.erb
<div id="minicart">
  <% @body_id = 'cart' %>
  <% current_order = Spree::Order.find_by(id: session[:order_id]) %>

  <div class="minicart-wrapper" data-hook="outside_minicart_form">
    <% if current_order.nil? || current_order.line_items.empty? %>

        <div id="minicart-details" data-hook="minicart_details" class="clearfix">
          <div data-hook="empty_minicart">
            <div class="empty"><%= Spree.t(:your_cart_is_empty) %></div>
            <%= link_to Spree.t(:continue_shopping), '/products', :class => 'btn-primary continue' %>
          </div>
        </div>

        <a class="mobile-only close-cart">Close</a>

        <div class="mobile-only" id="update-minicart"></div>

    <% else %>

        <div id="minicart-details" data-hook="minicart_details" class="clearfix">
          <div class="subtotal"><%= Spree.t(:subtotal) %>:
            <span class="order-total"><%= current_order.display_item_total %></span></div>
          <%= link_to Spree.t(:checkout), spree.checkout_path, :class => 'btn-primary checkout', :id => 'checkout-link' %>
        </div>
        <a class="mobile-only close-cart">Close</a>
        <%= form_for current_order, :url => spree.update_cart_path, :html => {:id => 'update-minicart'}, :remote => true do |order_form| %>

            <div data-hook="inside_minicart_form">
              <div data-hook="minicart_items" class="clearfix">
                <%#= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
                <% if @order && @order.errors.any? %>

                    <div id="errorExplanation" class="errorExplanation" data-hook>
                      <ul>
                        <% @order.errors.full_messages.each do |msg| %>
                            <li class="error-message"><%= msg %></li>
                        <% end %>
                      </ul>
                    </div>
                <% end %>
                <ul id='minicart-items' class="clearfix">
                  <%= order_form.fields_for :line_items do |item_form| %>
                      <%= render :partial => 'alchemy/shared/minicart_line_items', :locals => {:variant => item_form.object.variant, :line_item => item_form.object, :item_form => item_form, :current_order => current_order} if item_form.object.variant %>
                  <% end %>
                </ul>
              </div>
            </div>

        <% end %>
    <% end %>
  </div>
</div>

app/views/alchemy/shared/_minicart_line_items.html.erb
<li class="<%= cycle('one', 'two', 'three', 'four') %>">
  <div class='minicart-actions' data-hook="minicart_item_actions">
    <div class='minicart-delete' data-hook="minicart_item_delete">
      <%= link_to '&#10005;'.html_safe, '#', :class => 'delete', :id => "delete_#{dom_id(line_item)}" %>
    </div>
  </div>

  <%= content_tag :div, class: 'minicart-content', data: {product_name: variant.product.name, variant_name: variant.options_text, price: variant.price, quantity: line_item.quantity, position: line_item.order.line_items.index(line_item)} do -%>
      <div data-hook="minicart_item_image" class="item-image-wrapper">
        <% if variant.images.length == 0 %>
            <%= link_to image_tag(variant.product.images[0].attachment.url(:small)), product_path(variant.product) %>
        <% else %>
            <%= link_to image_tag(variant.images.first.attachment.url(:small)), product_path(variant.product) %>
        <% end %>
      </div>
      <div class='minicart-item-description' data-hook="minicart_item_description">
        <div class="item-name" data-hook="minicart_item_name">
          <div class="product-name"><%= link_to variant.product.name, product_path(variant.product) %></div>
        </div>
        <div class="item-total" data-hook="minicart_item_total">
          <%= Spree::Money.new((line_item.price * line_item.quantity), {:currency => "USD"}).to_s unless line_item.quantity.nil? %>
        </div>
        <div class="variant-qty">
          <span class="line-item-quantity notification"><span><%= "#{line_item.quantity}" %></span></span>
          <span class="item-variant"><%= variant.options_value %></span>

          <div class="change-qty">Change Qty</div>
        </div>

      </div>
  <%- end %>

  <div data-hook="minicart_item_quantity" class="qty-wrapper">
    <div class="qty-field-wrapper">
      <span class="close"></span>
      Quantity
      <div class="qty-field"></div>
      <%#= text_field_tag :quantity, "", :class => 'title '%>
    </div>
    <input type='button' value='&minus;' class='qty-btn qty-change qtyminus' field='quantity'/>
    <input type='submit' value='OK' class="qty-btn qtysubmit" id="qty-submit"/>
    <input type='button' value='+' class='qty-btn qty-change qtyplus' field='quantity'/>
    <%= item_form.hidden_field :quantity, :min => 0, :class => "line_item_quantity" %>
  </div>


</li>

app/views/alchemy/shared/_newsletter_modal.html.erb
<div class="email_capture_modal" id="email_capture_modal_712"><script>
  var google_analytics_event_label = 'index_modal';
</script>
<div class="modal-wrapper spring2015">
  <div class="modal-overlay in"></div>
  <div class="modal-container bg-color purple in">
    <div class="overlay"></div>
    <div class="modal-container-inner">
      <a class="modal-dismiss" href="#">Close</a>
      <h3><p>Tracksmith:<br>Now Co-Ed</p></h3>
      <h4><p class="p1"><span class="s1">Subscribe to find out first about upcoming launches and other surprises</span></p></h4>
      <form accept-charset="UTF-8" action="/mailchimp/subscribe" class="email-form" data-remote="true" id="email-capture-modal" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"></div>
            <input class="email-input" id="email" name="email[address]" placeholder="Enter Your Email" type="email">
            <input class="btn-primary" name="commit" type="submit" value="Sign Up">
      </form>
      <div id="response"></div>
    </div>
  </div>
</div>
</div>

app/views/alchemy/shared/_product.html.erb
<div class="product-module">

  <div class="product-image-wrapper">
    <div id="product-images" data-hook="product_images">
      <div id="main-image" data-hook>

        <%if product.images.any?  %>
            <%= image_tag product.images[0].attachment.url(:large), :itemprop => "image"%>
          <%elsif product.variant_images.any? %>
            <%= image_tag product.variant_images[0].attachment.url(:large), :itemprop => "image"%>
          <%else %>
            <p>"placeholder image"</p>
          <% end %>

      </div>

      <div id="thumbnails" data-hook>
      <%# no need for thumbnails unless there is more than one image %>
      <% if (product.images + product.variant_images).uniq.size > 1 %>
        <ul id="product-thumbnails" class="thumbnails inline" data-hook>
        <% product.images.each do |i| %>
          <li class='tmb-all <%= i.variant_html_classes %>' data-products="[<%= i.variant_html_attr %>]">
            <%= link_to(image_tag(i.attachment.url(:mini)), i.attachment.url(:product)) %>
          </li>
        <% end %>

        <% if product.has_variants? %>
          <% product.variant_images.each do |i| %>
            <% next if product.images.include?(i) %>
             <li class='vtmb <%= i.variant_html_classes %>' data-products="[<%= i.variant_html_attr %>]">
              <%= link_to(image_tag(i.attachment.url(:mini)), i.attachment.url(:product)) %>
            </li>
          <% end %>
        <% end %>
        </ul>
      <% end %>
      </div>

    </div>
  </div>

  <div class="product-info-wrapper">
    <h3 class="didot"><%= product.name %></h3>

    <div class="price"><%= Spree::Money.new(product.price).to_s %></div>
    <p><%=product.description%></p>



    <%= form_for :order, :url => spree.populate_orders_url, :remote => true do |f| %>

      <div id="inside-product-cart-form" data-hook="inside_product_cart_form" itemprop="offers" itemscope itemtype="http://schema.org/Offer">

      <% if product.variants_and_option_values.any? %>
      <% if product.has_variants? %>

      <% index = 0 %>

      <div id="product-variants" class="medium-6 columns">
        <% product.grouped_option_values.each do |type, values| %>
        <div id="<%= dom_id(type) %>" class="variant-options index-<%= index %>">
          <%= label_tag 'option-value-name', Spree.t(:select_a, :index => index + 1, :name => type.presentation.capitalize) %>
          <ul class="variant-option-values inline-list" data-group="<%= index %>">
            <% values.sort_by(&:position).each do |value| %>
            <% classes = ["option-value"] %>
            <% unless (variants = product.variants_for_option_value(value)).empty? %>
            <% classes << ( variants.any? { |v| v.in_stock? } ? "in-stock" : "out-of-stock" ) if index == 0 %>
              <%
                classes = classes.join(" ")
                classes = classes + " " + "btn btn-secondary"
              %>
              <% variant_ids = [] %>

              <% variants.each do |v| %>
                <% (variant_ids ||= []) << v.id if v.in_stock? %>
              <% end %>

              <% index == 0 ? (disabled = false) : (disabled = true) %>
              <%if type.presentation == 'Size' %>
              <li><%= button_tag(value.presentation, { :class => classes, :disabled => disabled, :type => 'button', :data => {products: variant_ids, group: index} }) %></li>
              <%else %>
              <li><span class="<%= classes %>" data-products="<%= variant_ids %>" data-group="<%=index%>"><%=value.presentation%></span></li>

              <%end%>
                <% end %>
              <% end %>
            </ul>
          </div>
          <% index += 1 %>
        <% end %>
      </div>

      <%= hidden_field_tag "variant_id", "", :id => "variant_id", :class => "hidden" %>
      <% end %>

      <div class="add-to-cart">
        <%= number_field_tag :quantity, 1, :class => 'title', :min => 1 %>
        <%= button_tag :class => 'btn btn-primary', :id => 'add-to-cart-button', :type => :submit do %>
          <%= Spree.t(:add_to_cart) %>
        <% end %>
      </div>

    <% end %>
    </div>
  <%end %>
  </div>

</div>