config/routes.rb
Track::Application.routes.draw do

  get "maildev" => 'emaildev#index'

  get "welcome" => "application#welcome", path: "/shop/welcome/"
  get "return_order_test" => "application#return_order_test", path: 'shop/return_order_test'
  post "return_order" => "application#return_order", path: 'shop/return_order'
  post "mailchimp/subscribe" => "mailchimp#subscribe"
  post "mailchimp/subscribe_footer" => "mailchimp#subscribe_footer"
  post "mailchimp/notify_me" => "mailchimp#notify_me"

  resources 'referrals', except: [:delete, :update, :edit]
  post 'referrals/subscribe' => 'referrals#subscribe', as: :subscribe_referral
  get 'spreadtheword' => 'referrals#new', as: :create_referral

  match "/products", :to => redirect("/men"), via: :get
  match "/womens", :to => redirect("/women"), via: :get

  get "men" => "application#men", path: "/men"
  get "women" => "application#women", path: "/women"

  mount Spree::Core::Engine, :at => '/shop'

  mount Alchemy::Engine => '/', :as => 'alchemy'

  Spree::Core::Engine.draw_routes

end

app/models/spree/calculator/tiered_flat_rate_shipping.rb
module OrderWeightCategory
  Light = 1
  Default = 2
  Heavy = 4
end

class Spree::Calculator::TieredFlatRateShipping < Spree::ShippingCalculator
  preference :light_cost, :decimal, default: -1
  preference :default_cost, :decimal, default: -1
  preference :heavy_cost, :decimal, default: -1

  def self.description
    return "Tiered Flat Rate"
  end
  
  def compute(object=nil)
    case @order_weight_category
    when OrderWeightCategory::Heavy
      return self.preferred_heavy_cost
    when OrderWeightCategory::Light
      return self.preferred_light_cost
    else
      return self.preferred_default_cost
    end
  end

  def available?(object)
    @order_weight_category = calculateOrderWeightCategory(object.order)

    case @order_weight_category
    when OrderWeightCategory::Heavy
      return self.preferred_heavy_cost != -1
    when OrderWeightCategory::Light
      return self.preferred_light_cost != -1
    else
      return self.preferred_default_cost != -1
    end
  end

  def isHeavy?(product) 
    return !product.properties.select {|property| property.name == "heavy"}[0].nil?
  end

  def isLight?(product) 
    return !product.properties.select {|property| property.name == "light"}[0].nil?
  end

  def calculateOrderWeightCategory(order) 
    is_light_order = true # All products must be light.
    is_heavy_order = false # Only 1 has to be heavy.

    order.line_items.each do |line_item|
      product = line_item.product

      unless isLight?(product)
        is_light_order = false
      end

      if isHeavy?(product)
        return OrderWeightCategory::Heavy
      end
    end

    if is_light_order
      return OrderWeightCategory::Light
    end

    # Wasn't light or heavy return default
    return OrderWeightCategory::Default
  end
end

app/models/spree/image_decorator.rb
Spree::Image.class_eval do
  attachment_definitions[:attachment][:styles] = {
    :mini => '100x100>', 
    :small => '160x160>', # images in cart
    :product => '500x500>', # products page?
    :large => '750x750>' # product detail page
  }
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do

	include MandrillHelper

	def deliver_order_confirmation_email
		if user
    	sendMandrillMail({
				template: '/mandrill/order_confirmation',
				subject: I18n.t('user_mailer.order_confirmed.subject'),
				locals: { order: self },
				to: [{
		         :email=> self.email,
		         :name=> "#{self.bill_address.firstname} #{self.bill_address.lastname}"
		       }]
				})

    end
    update_column(:confirmation_delivered, true)
  end

  def current_state_number
  	self.checkout_steps.index state
  end

end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do

  def option_values
    @_option_values ||= Spree::OptionValue.for_product(self)
  end

  def grouped_option_values
    @_grouped_option_values ||= option_values.group_by(&:option_type)
    @_grouped_option_values.sort_by { |option_type, option_values| option_type.position }
  end

  def variants_for_option_value(value)
    @_variant_option_values ||= variants.includes(:option_values)
    @_variant_option_values.select { |i| i.option_value_ids.include?(value.id) }
  end

  def variant_options_hash
    return @_variant_options_hash if @_variant_options_hash
    hash = {}
    variants.includes(:option_values).each do |variant|
      variant.option_values.each do |ov|
        otid = ov.option_type_id.to_s
        ovid = ov.id.to_s
        hash[otid] ||= {}
        hash[otid][ovid] ||= {}
        hash[otid][ovid][variant.id.to_s] = variant.to_hash
      end
    end
    @_variant_options_hash = hash
  end

end

app/models/spree/shipment_decorator.rb
Spree::Shipment.class_eval do

	include MandrillHelper
	 def send_shipped_email
  	sendMandrillMail({
			template: '/mandrill/order_shipped',
			subject: I18n.t('user_mailer.order_shipped.subject'),
			locals: { shipment: self },
			to: [{
	         :email=> self.order.email,
	         :name=> "#{self.order.bill_address.firstname} #{self.order.bill_address.lastname}"
	       }]
			})
  end
end

app/models/spree/user_decorator.rb
Spree::User.class_eval do

	after_create :send_welcome_email

  def alchemy_roles
    if self.has_spree_role?('admin')
      %w(admin)
    end
  end

  def send_welcome_email
  	UserMailer.welcome(self.id).deliver
  end
  
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
    def options_value
      values = self.option_values.sort do |a, b|
        a.option_type.position <=> b.option_type.position
      end

      values.map! do |ov|
        "#{ov.presentation}"
      end

      values.to_sentence({ words_connector: ", ", two_words_connector: ", " })
    end


end

app/controllers/spree/checkout_controller_decorator.rb
Spree::CheckoutController.class_eval do
  def update

	  if @order.update_from_params(params, permitted_checkout_attributes)
	    persist_user_address
	    unless @order.next
	      flash[:error] = @order.errors.full_messages.join("\n")
  			# raise params[:payment_source].to_yaml
	      redirect_to checkout_state_path(@order.state) and return
	    end

	    if @order.completed?
	    	session[:order_id] = nil
	      @current_order = nil
	      flash.notice = Spree.t(:order_processed_successfully)
	      flash[:order_completed] = true
	      redirect_to completion_route
	    else
	      redirect_to checkout_state_path(@order.state)
	    end
	  else
	    render :edit
	  end
	end

end

app/controllers/spree/orders_controller_decorator.rb
Spree::Api::OrdersController.class_eval do

	def apply_coupon_code
    find_order
    authorize! :update, @order, order_token

    # Prelaunch Coupons
    prelaunch_coupons = PrelaunchCoupon.all.where(code: params[:coupon_code])
    unless prelaunch_coupons.empty?
    	prelaunch_coupon = prelaunch_coupons.first
    	if prelaunch_coupon[:applied] == 'f'
	    	params[:coupon_code] = "prelaunch-#{prelaunch_coupon[:level]}"
		    prelaunch_coupon[:applied] = 't'
		    prelaunch_coupon[:order_id] = @order[:id]
		    prelaunch_coupon.save!
		  elsif prelaunch_coupon[:applied] == 't' and prelaunch_coupon[:order_id] == @order[:id]
		  	params[:coupon_code] = "prelaunch-#{prelaunch_coupon[:level]}"
		  end
    end

    @order.coupon_code = params[:coupon_code]
    @handler = Spree::PromotionHandler::Coupon.new(@order).apply
    status = @handler.successful? ? 200 : 422
    render "spree/api/promotions/handler", :status => status
  end
end

app/controllers/spree/shipstation_controller_decorator.rb
Spree::Shipment.class_eval do

  def send_shipped_email
    # Spree::ShipmentMailer.shipped_email(self.id).deliver if Spree::Config.send_shipped_email
    # if user
    	sendMandrillMail({
				template: '/mandrill/order_shipped',
				subject: I18n.t('user_mailer.order_shipped.subject'),
				locals: { shipment: self },
				to: [{
		         :email=> self.order.email,
		         :name=> "#{self.order.bill_address.firstname} #{self.order.bill_address.lastname}"
		       }]
				})

    # end
  end

end

app/controllers/spree/store_controller_decorator.rb
Spree::StoreController.class_eval do
  def apply_coupon_code
    if params[:order] && params[:order][:coupon_code]

      # Prelaunch Coupons
      prelaunch_coupons = PrelaunchCoupon.all.where(code: params[:order][:coupon_code])
      unless prelaunch_coupons.empty?
        prelaunch_coupon = prelaunch_coupons.first
        if prelaunch_coupon[:applied] == 'f'
          params[:order][:coupon_code] = "prelaunch-#{prelaunch_coupon[:level]}"
          prelaunch_coupon[:applied] = 't'
          prelaunch_coupon[:order_id] = @order[:id]
          prelaunch_coupon.save!
        elsif prelaunch_coupon[:applied] == 't' and prelaunch_coupon[:order_id] == @order[:id]
          params[:order][:coupon_code] = "prelaunch-#{prelaunch_coupon[:level]}"
        end
      end

      @order.coupon_code = params[:order][:coupon_code]

      handler = Spree::PromotionHandler::Coupon.new(@order).apply

      if handler.error.present?
        flash.now[:error] = handler.error
        respond_with(@order) { |format| format.html { render :edit } } and return
      elsif handler.success
        flash[:success] = handler.success
      end
    end
  end

end

app/controllers/spree/user_registrations_controller_decorator.rb
Spree::UserRegistrationsController.class_eval do
  def create
    @user = build_resource(spree_user_params)
    @source = params[:spree_user][:source]
    if resource.save
      # Add user to mail list

      sign_up_params = params[:sign_up]
      if sign_up_params
        if sign_up_params[:email_opt_in]
          begin
            @mc.lists.subscribe(MAILCHIMP_CONFIG['main_mail_list'], {:email => @user.email}, nil, 'html', false, false, true, true)
          rescue => e
            logger.warn "Unable to add user to mailchimp #{e}"
          end
        end
      end

      set_flash_message(:notice, :signed_up)
      sign_in(:spree_user, @user)
      session[:spree_user_signup] = true
      associate_user

      if @source == 'signup'
        respond_with resource, location: redirect_back_or_default(alchemy.root_url)
      else
        redirect_to redirect_back_or_default(checkout_path)
      end

    else
      clean_up_passwords(resource)
      render :error
    end
  end

  def redirect_back_or_default(default)
    path = session["spree_user_return_to"]
    session["spree_user_return_to"] = nil
    path || default
  end
end

app/controllers/spree/user_sessions_controller_decorator.rb
Spree::UserSessionsController.class_eval do
  
  # using from ginlane's spree_auth_devise fork to customize the sign in and sign out redirects

  def after_sign_in_path_for(user)
    spree.account_path
  end


  def after_sign_out_path_for(resource_or_scope)
    "/"
  end

  def create
    authenticate_spree_user!

    if spree_user_signed_in?
      respond_to do |format|
        format.html {
          flash[:success] = Spree.t(:logged_in_succesfully)
          redirect_back_or_default(after_sign_in_path_for(spree_current_user))
        }
        format.js {
          render :json => {:user => spree_current_user,
                           :ship_address => spree_current_user.ship_address,
                           :bill_address => spree_current_user.bill_address}.to_json
        }
      end
    else
      respond_to do |format|
        format.html {
          flash.now[:error] = t('devise.failure.invalid')
          render :error
        }
        format.js {
          render :json => { error: t('devise.failure.invalid') }, status: :unprocessable_entity
        }
      end
    end
  end

  def new
    super
    @user = resource
  end

end

app/helpers/spree/addresses_helper.rb
module Spree::AddressesHelper
  def address_field(form, method, address_id = "b", &handler)
    content_tag :p, :id => [address_id, method].join, :class => "field" do
      if handler
        handler.call
      else
        is_required = Spree::Address.required_fields.include?(method)
        # separator = is_required ? '<span class="required">*</span><br />' : '<br />'
        # form.label(method) + separator.html_safe +

        case method
        when :firstname
          placeholder = Spree.t(:first_name)+" *"
        when :lastname
          placeholder = Spree.t(:last_name)+" *"
        when :address1
          placeholder = Spree.t(:street_address)+" *"
        when :address2
          placeholder = Spree.t(:street_address_2)
        when :city
          placeholder = Spree.t(:city)+" *"
        when :zipcode
          placeholder = Spree.t(:zipcode)+" *"
        when :phone
          placeholder = Spree.t(:phone)+" *"
        end

        form.text_field(method, :class => is_required ? 'required' : nil, :placeholder => placeholder)
      end
    end
  end

  def address_state(form, country, address_id)
    country ||= Spree::Country.find(Spree::Config[:default_country_id])
    have_states = !country.states.empty?
    state_elements = [
      form.collection_select(:state_id, country.states.order(:name),
                            :id, :name,
                            {:include_blank => 'State'},
                            {:class => have_states ? "required" : "hidden",
                            :disabled => !have_states}) +
      form.text_field(:state_name,
                      :class => !have_states ? "required" : "hidden",
                      :disabled => have_states)
      ].join.gsub('"', "'").gsub("\n", "")

      content_tag(:noscript, form.text_field(:state_name, :class => 'required')) +
      javascript_tag("document.write(\"#{state_elements.html_safe}\");")
  end
end

app/helpers/spree/authentication_helpers.rb
module Spree
  module AuthenticationHelpers
    def self.included(receiver)
      receiver.send :helper_method, :spree_login_path
      receiver.send :helper_method, :spree_signup_path
      receiver.send :helper_method, :spree_logout_path
      receiver.send :helper_method, :spree_current_user
    end

    # def spree_current_user
    #   current_user
    # end

    # def spree_login_path
    #   main_app.login_path
    # end

    # def spree_signup_path
    #   main_app.signup_path
    # end

    # def spree_logout_path
    #   main_app.logout_path
    # end
  end
end

ApplicationController.send :include, Spree::AuthenticationHelpers

app/helpers/spree/base_helper_decorator.rb
module Spree
  module BaseHelper

    # overriding the Spree default to make the number of items in cart style-able

    def link_to_cart(text = nil)
      text = text ? h(text) : Spree.t('cart')
      css_class = nil

      if simple_current_order.nil? or simple_current_order.item_count.zero?
        text = "#{text}"
        css_class = 'empty'
      else
        text = "<span class='cart-text'>#{text}</span><span class='item-count notification'><span>#{simple_current_order.item_count}</span></span>"
        css_class = 'full'
      end

      link_to text.html_safe, spree.cart_path, :class => "cart-info #{css_class}"
    end
  end
end

app/helpers/spree/checkout_helper.rb
module Spree
  module CheckoutHelper
    def checkout_states
      @order.checkout_steps
    end

    def checkout_progress
      states = checkout_states
      items = states.map do |state|
        text = Spree.t("order_state.#{state}").titleize

        css_classes = []
        current_index = states.index(@order.state)
        state_index = states.index(state)
        state_number = state_index+1

        if state_index < current_index
          css_classes << 'completed'
          text = link_to text, checkout_state_path(state)
        end

        css_classes << 'next' if state_index == current_index + 1
        css_classes << 'current' if state == @order.state
        css_classes << 'first' if state_index == 0
        css_classes << 'last' if state_index == states.length - 1
        css_classes << 'disabled' if state_index > current_index

        # It'd be nice to have separate classes but combining them with a dash helps out for IE6 which only sees the last class
        content_tag :li, class: css_classes.join('-') do
          content_tag('span', state_number, class: 'number') + content_tag('span', text, class: 'state') 
        end

      end
      content_tag('ol', raw(items.join("\n")), class: 'checkout-breadcrumbs progress-steps', id: "checkout-step-#{@order.state}")
    end
  end
end

app/helpers/spree/orders_helper.rb
require 'truncate_html'
require 'app/helpers/truncate_html_helper'

module Spree
  module OrdersHelper
    include TruncateHtmlHelper

    def truncated_product_description(product)
      truncate_html(raw(product.description))
    end

    def order_just_completed?(order)
      flash[:order_completed] && order.present?
    end
  end
end

app/helpers/spree/products_helper.rb
module Spree
  module ProductsHelper

    def product_path(product)
      alchemy.root_url + "products/#{product.slug}"
    end

    def cache_key_for_products
      max_updated_at = @products.maximum(:updated_at).to_s(:number)
      "#{current_currency}/spree/products/all-#{params[:page]}-#{max_updated_at}"
    end

    def line_item_description_text (var)
      ""
    end
  end
end

app/views/spree/users/_returns.html.erb
<%= form_tag "/shop/return_order", id: "ts-return-form", remote: true do %>
	<div class='radio'>
		<div> Please select: </div>
		<p>
		<%= radio_button_tag(:type, "return") %>
		<%= label_tag(:type_return, "Return", class: 'return_label') %>

		<span class="divider">
			<span class="horizontal"></span><span class="or">or</span><span class="horizontal"></span>
		</span>
		<%= radio_button_tag(:type, "exchange") %>
		<%= label_tag(:type_exchange, "Exchange", class: 'return_label') %>
		<p>
	</div>
	<p>
  <%= text_field_tag "name", nil,  placeholder: "* Full Name" %></p>
  <p><%= email_field_tag "email", @user.email, placeholder: "* Email" %></p>

  <!-- creating array of order numbers -->
	<% order_number_array = @user.orders.map {|order| [order.number, order.number]}%>
	<p><%= select_tag "order_number", options_for_select(order_number_array), {prompt: '* Select Order Number'} %></p>

	<p><%= text_field_tag "replacing", nil,  placeholder: "* Item Exchanging (ex. The Grayboy)", class: 'exchange-input' %></p>
	<p><%= text_field_tag "desired", nil, placeholder: "* Desired Variant (ex. Olive, Small)", class: 'exchange-input' %></p>

  <p><%= text_area_tag "comments", nil,  {:placeholder => "Additional Comments"} %></p>
  <%= hidden_field_tag "email", @user.email %>

  <%= submit_tag "Send", {:class => "btn-primary"}%>
	<p class="required">* Required</p>

<% end %>

app/views/spree/users/_store_credits.html.erb
<div data-hook="account_credits" class="account-section" id="credits">
  <h3><%= Spree.t("store_credits") %></h3>
  <div class="line"></div>
  <div class="account-sub-section">
        <h4>Balance</h4>
  <% if @user.has_store_credit? %>
    <div class="current-balance">Your current balance is <%= number_to_currency @user.store_credits_total %></div>
    <%else%>
    <div class="current-balance">You do not have any store credit.</div>
    <%end%>
    <% if @orders_with_store_credit.present? %>
      <h3><%= Spree.t('orders_with_store_credit') %></h3>
      <table class="order-summary">
        <thead>
          <tr>
            <th><%= Spree.t("order_number") %></th>
            <th><%= Spree.t("order_date") %></th>
            <th><%= Spree.t("status") %></th>
            <th><%= Spree.t("customer") %></th>
            <th><%= Spree.t("total") %></th>
            <th><%= Spree.t("store_credit") %></th>
          </tr>
        </thead>
        <tbody>
        <% @orders_with_store_credit.each do |order| %>
          <tr class="<%= cycle('even', 'odd') %>">
            <td><%= link_to order.number, order_url(order) %></td>
            <td><%=order.created_at.to_date%></td>
            <td><%= Spree.t(order.state).titleize %></td>
            <td><%= order.user.email if order.user %></td>
            <td><%= number_to_currency order.total %></td>
            <td><%= number_to_currency order.store_credit_amount %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <%end%>
  </div>
</div>

app/views/spree/users/edit.html.erb
<div class="account-page account-edit">
  <ul class="account-links">
    <li><a class="account-link" href="/shop/account#dashboard">Account Information</a></li>
    <li><a class="account-link" href="/shop/account#addresses">Address Book</a></li>
    <li><a class="account-link" href="/shop/account#orders">Order History</a></li>
    <li><a class="account-link" href="/shop/account#credits">Credits</a></li>
    <li><a class="account-link" href="/shop/account#returns">Returns &amp; Exchanges</a></li>
  </ul>
  <section class="account-info">
    <div class="edit-user">
      <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user } %>

      <h3><%= Spree.t(:editing_user) %></h3>
        <div class="line"></div>

      <%= form_for Spree::User.new, :as => @user, :url => spree.user_path(@user), :method => :put do |f| %>
        <%= render :partial => 'spree/shared/user_form', :locals => { :f => f, :source => 'account' } %>
        <p>
          <%= f.submit Spree.t(:update), :class => 'button primary' %>
        </p>
      <% end %>
    </div>
  </section>
</div>

app/views/spree/users/show.html.erb
<div id="account-page" class="account-page account-main">



  <ul class="account-links">
    <li><a class="account-link sub-link" href="#dashboard">Account Information</a></li>
    <li><a class="account-link sub-link" href="#addresses">Address Book</a></li>
    <li><a class="account-link sub-link" href="#orders">Order History</a></li>
    <li><a class="account-link sub-link" href="#credits">Credits</a></li>
    <li><a class="account-link sub-link" href="#returns">Returns &amp; Exchanges</a></li>
  </ul>
  <section class="account-info">
    <div data-hook="account_dashboard" class="account-section active" id="dashboard">
      <h3>Account Information</h3>
      <div class="line"></div>
      <div class="account-sub-section">
        <h4>User Information</h4>
        <dl id="user-info">
          <dd><%= @user.email %></dd>
          <dd><%= link_to Spree.t(:edit), spree.edit_account_path %></dd>
        </dl>
      </div>
    </div>


    <div data-hook="account_my_orders" class="account-section" id="orders">
      <h3>Order History</h3>
      <div class="line"></div>
      <% if @orders.present? %>
        <table class="order-summary">
          <thead>
          <tr>
            <th class="order-date"><%= Spree.t(:date) %></th>
            <th class="order-recipient">Recipient </th>
            <th class="order-number"><%= I18n.t(:number, :scope => 'activerecord.attributes.spree/order') %></th>

        <!-- <th class="order-status"><%#= Spree.t(:status) %></th> -->
            <!--     <th class="order-payment-state"><%#= Spree.t(:payment_state) %></th>-->
            <th class="order-shipment-state">Status </th>
            <th class="order-total"><%= Spree.t(:total) %></th>
          </tr>
          </thead>
          <tbody>
          <% @orders.each do |order| %>

            <tr>
              <td class="order-date"><%=  order.completed_at.to_date.strftime("%D")   %></td>
              <td class="order-recipient"><%= order.ship_address.firstname %> <%= order.ship_address.lastname %></td>
              <td class="order-number"><%= link_to order.number, order_url(order) %></td>
            <!-- <td class="order-status"><%#= Spree.t("order_state.#{order.state}").titleize %></td> -->
            <!-- <td class="order-payment-state"><%#= Spree.t("payment_states.#{order.payment_state}").titleize if order.payment_state %></td> -->
            <td class="order-shipment-state"><%= Spree.t("shipment_states.#{order.shipment_state}").titleize if order.shipment_state %></td>
              <td class="order-total"><%= order.display_total %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% else %>
        <div class="no-results"><%= Spree.t(:you_have_no_orders_yet) %></div>
      <% end %>
      <br />

    </div>

    <div class="account-section" id="returns">
      <h3>Returns &amp; Exchanges</h3>
      <div class="line"></div>
      <div class="returns-text">
        To make a return, please select 'Return' below and fill out the following form. <br/>
        <br />
        To make an exchange, please select 'Exchange' below, and in the fields provided, specify the item you'd like to exchange and your desired replacement variant. <br/>
      </div>
      <%= render partial: 'returns' %>
      <div id="response" class="return-submitted"></div>
    </div>



  </section>

</div>